### ISSUE TITLE
Guess the dominoes needs to be marginal larger

### ISSUE THREAD

**Issue by buschsom** [wraybowling/shaper_taper#1]
Hi,
I have cut a circle being 148 mm in diameter  (as designed) using original Shaper Tape and my Shaper.
Using same file, material etc, and a print from shaper-taper instead of the original, I cut a new circle which meassured  only 140.7 mm (+/-). 

**Could the printet shaper-taper be marginal smaller that the original domino's from Shaper?** 

The length of original domino is 43 mm, while the printet one is 42 mm. So the printet domino's may need to be a few % larger.
PS: I did print out on A4 paper instead of 8x11" US letter.

**Comment by buschsom** [comment]
As per https://gist.github.com/Fordi/97087480faf990e29fc5985fc02ce2f6 the domino's should in mm be:  "width="43" height="12.7""
I have tried printing out on A4 paper, and in landscape it print in the rigth size.  Did make a testing with my Shaper

Made a 100x100mm square: Original domino's resultet in exact size, the 43x12.7 domino's resulted in 98x99mm. So that means it should be 43x12,82 (something like 1.693x0.505 inches).
Seem like the dimentions of the domino's are both determinatorts.
Will be happy to confirm via testing with the Shaper.

**Comment by wraybowling** [comment]
The size of the paper is irrelevant. Actually even the size of the black part of the domino is largely irrelevant. what truly matters is the spacing between the dots. I'll compare my measurements against your link. Thank you for providing it.

**Comment by wraybowling** [comment]
Okay. The size defined by the web browser is being printed out at a size different than real world units. This has to do with strange discrepancies in how big a "screen inch" is. Or, in other words, an inch is as big as the browser thinks an inch looks on the viewport you're looking at. That doesn't mean it's an inch, but that it thinks you'll believe it looks like an inch. I thought this was resolved with latest browsers such that a "paper viewport" would set that scalar such that 1in actually equals 1in, but apparently not. Furthermore, measurements I was lead to believe were correct for the size of real tape were not ever correct. Optically measuring the tape on a flatbed scanner, the dots were always meant to be simply 0.5in, spaced 0.5in apart, with 0.5in of black border, rounded with 0.5in corners. I wish I'd never believed anyone else's measurements. Anyway, I think that there are ways of correcting the viewport scale with a meta tag. I will look in to that and keep printing test pages until the size of the domino printed matches the size of the domino i asked for.

<img width="739" alt="Screen Shot 2021-02-01 at 2 16 44 PM" src="https://user-images.githubusercontent.com/1120619/106507403-00bb9780-6499-11eb-930a-621415577462.png">

**Comment by wraybowling** [comment]
I've fixed all measurements so that printing from Chrome produces a domino accurate within 0.001in
<img width="1014" alt="Screen Shot 2021-02-01 at 6 44 10 PM" src="https://user-images.githubusercontent.com/1120619/106532074-7fc2c700-64bd-11eb-9b6e-5ec30cf5440f.png">
